# Fraud Detection

### In this mini project I wanted to use Logistic Regression :)

In [ ]:
import seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
# Load the data
df = pd.read_csv("C:/Programowanie/codecademy_projects/data_sets_codecademy/fraud_detection.csv")
df.head(5)

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [9]:

df['isPayment'] = df['type'].apply(lambda x: 1 if x in ['PAYMENT', 'DEBIT'] else 0)
print(df['isPayment'].value_counts())



isPayment
0    4169693
1    2192927
Name: count, dtype: int64


In [10]:
# Create isMovement field
df['isMovement'] = df['type'].apply(lambda x: 1 if x in ['CASH_OUT', 'TRANSFER'] else 0)
print(df['isMovement'].value_counts())

isMovement
0    3592211
1    2770409
Name: count, dtype: int64


In [11]:
# Create accountDiff field
df['accountDiff'] = np.abs(df['oldbalanceOrg'] - df['oldbalanceDest'])

# Create features and label variables
x = df[['amount', 'isPayment', 'isMovement', 'accountDiff']]

y = df['isFraud']

In [16]:
df.head(5)

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  \
0  M1979787155             0.0             0.0        0               0   
1  M2044282225             0.0             0.0        0               0   
2   C553264065             0.0             0.0        1               0   
3    C38997010         21182.0             0.0        1               0   
4  M1230701703             0.0             0.0        0               0   

   isPayment  isMovement  accountDiff  
0          1           0     170136.0  
1          1           0      21249.0  
2          0           1        181.0  
3          0           1      21001.0  
4          1           0      41554.0

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

s = StandardScaler()
f_train = s.fit_transform(x_train)
f_test = s.transform(x_test)

In [14]:
# Fit the model to the training data
model = LogisticRegression()
model.fit(x_train, y_train)


# Score the model on the training data
print(model.score(x_train, y_train))

# Score the model on the test data
print(model.score(x_test, y_test))

# Print the model coefficients
print(model.coef_)

0.9986818098743689
0.9987002209781505
[[ 4.45584262e-07 -5.26042439e+00 -3.87308208e-01 -2.16945919e-07]]


In [15]:
# New transaction data
random_transaction1 = np.array([123456.78, 0.0, 1.0, 54670.1])
random_transaction2 = np.array([98765.43, 1.0, 0.0, 8524.75])
random_transaction3 = np.array([543678.31, 1.0, 0.0, 510025.5])
random_transaction4 = np.array([927582758273851543678.31, 1.0, 0.0, 10510025.5])


# Combine new transactions into a single array
sample_transactions = np.stack((random_transaction1, random_transaction2, random_transaction3, random_transaction4))

# Normalize the new transactions
sample_transactions = s.transform(sample_transactions)

# Predict fraud on the new transactions
print(model.predict(sample_transactions))

# Show probabilities on the new transactions
print(model.predict_proba(sample_transactions))

[0 0 0 1]
[[9.20409950e-01 7.95900499e-02]
 [9.99997057e-01 2.94347343e-06]
 [9.99997057e-01 2.94347432e-06]
 [0.00000000e+00 1.00000000e+00]]


c:\Programowanie\.vscode\.conda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Programowanie\.vscode\.conda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Programowanie\.vscode\.conda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
